version: "3"
services:
  client-app:
    image: merlyne19/client
    stdin_open: true
    ports: 
      - "3000:3000"
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server-app
  server-app:
    image: merlyne19/server
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - e-meter
    volumes:
      - mongo-data:/data/db
networks:
  e-meter:
    driver: bridge
volumes:
  mongo-data:
    driver: local
